In [ ]:
import pandas as pd

In [ ]:
url_1 = 'https://raw.githubusercontent.com/ignaciogualini/Potenciales-datasets/refs/heads/main/datasets/ai_job_dataset.csv'
df1 = pd.read_csv(url_1, index_col='job_id')
df1.columns

Index(['job_title', 'salary_usd', 'salary_currency', 'experience_level',
       'employment_type', 'company_location', 'company_size',
       'employee_residence', 'remote_ratio', 'required_skills',
       'education_required', 'years_experience', 'industry', 'posting_date',
       'application_deadline', 'job_description_length', 'benefits_score',
       'company_name'],
      dtype='object')

In [ ]:
df1.head()

,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
job_id,,,,,,,,,,,,,,,,,,
AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [ ]:
url_2 = 'https://raw.githubusercontent.com/ignaciogualini/Potenciales-datasets/refs/heads/main/datasets/marketing_campaign.csv'
df2 = pd.read_csv(url_2, sep='\t', index_col='ID')
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2240 entries, 5524 to 9405
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year_Birth           2240 non-null   int64
 1   Education            2240 non-null   object
 2   Marital_Status       2240 non-null   object
 3   Income               2216 non-null   float64
 4   Kidhome              2240 non-null   int64
 5   Teenhome             2240 non-null   int64
 6   Dt_Customer          2240 non-null   object
 7   Recency              2240 non-null   int64
 8   MntWines             2240 non-null   int64
 9   MntFruits            2240 non-null   int64
 10  MntMeatProducts      2240 non-null   int64
 11  MntFishProducts      2240 non-null   int64
 12  MntSweetProducts     2240 non-null   int64
 13  MntGoldProds         2240 non-null   int64
 14  NumDealsPurchases    2240 non-null   int64
 15  NumWebPurchases      2240 non-null   int64
 16  NumCatalogPurchases  2240 non-null   int64
 17  NumStorePurchases    2240 non-null   int64
 18  NumWebVisitsMonth    2240 non-null   int64
 19  AcceptedCmp3         2240 non-null   int64
 20  AcceptedCmp4         2240 non-null   int64
 21  AcceptedCmp5         2240 non-null   int64
 22  AcceptedCmp1         2240 non-null   int64
 23  AcceptedCmp2         2240 non-null   int64
 24  Complain             2240 non-null   int64
 25  Z_CostContact        2240 non-null   int64
 26  Z_Revenue            2240 non-null   int64
 27  Response             2240 non-null   int64
dtypes: float64(1), int64(24), object(3)
memory usage: 507.5+ KB

In [ ]:
df2.head()

,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
ID,,,,,,,,,,,,,,,,,,,,,
5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,88,...,7,0,0,0,0,0,0,3,11,1
2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,1,...,5,0,0,0,0,0,0,3,11,0
4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,49,...,4,0,0,0,0,0,0,3,11,0
6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,4,...,6,0,0,0,0,0,0,3,11,0
5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,43,...,5,0,0,0,0,0,0,3,11,0

In [ ]:
url_3 = 'https://raw.githubusercontent.com/ignaciogualini/Potenciales-datasets/refs/heads/main/datasets/global-data-on-sustainable-energy.csv'
df3 = pd.read_csv(url_3, index_col='Entity')
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3649 entries, Afghanistan to Zimbabwe
Data columns (total 20 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Year                                                              3649 non-null   int64
 1   Access to electricity (% of population)                           3639 non-null   float64
 2   Access to clean fuels for cooking                                 3480 non-null   float64
 3   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 4   Financial flows to developing countries (US $)                    1560 non-null   float64
 5   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 6   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 7   Electricity from nuclear (TWh)                                    3523 non-null   float64
 8   Electricity from renewables (TWh)                                 3628 non-null   float64
 9   Low-carbon electricity (% electricity)                            3607 non-null   float64
 10  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 11  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 12  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 13  Renewables (% equivalent primary energy)                          1512 non-null   float64
 14  gdp_growth                                                        3332 non-null   float64
 15  gdp_per_capita                                                    3367 non-null   float64
 16  Density\n(P/Km2)                                                  3648 non-null   object
 17  Land Area(Km2)                                                    3648 non-null   float64
 18  Latitude                                                          3648 non-null   float64
 19  Longitude                                                         3648 non-null   float64
dtypes: float64(18), int64(1), object(1)
memory usage: 598.7+ KB

In [ ]:
df3.head()

,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
Entity,,,,,,,,,,,,,,,,,,,,
Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953